keys:
  # User keys
  - &tim age14y022wl4kddtsl6r54s8r3s6j75qc4e4tshhxw6sugy06qlvwa7sgrjfqs
  # Host keys
  - &laptop-02 age1tpm1qggj7xcx9f8a7aryv6cuwhxg0f67kxnrq0jd09amwudepachfk42z5n0g25
creation_rules:
  - path_regex: modules/boxen/laptop-02/secrets.yaml
    key_groups:
      - age:
          - *laptop-02
          - *tim
  - path_regex: modules/users/tim/secrets/secrets.yaml
    key_groups:
      - age:
          - *laptop-02
          - *tim
  - path_regex: modules/network/wifi.yaml
    key_groups:
      - age:
          - *laptop-02
          - *tim
stores:
  yaml:
    indent: 2
