keys:
  # User keys
  - &yubikey 5D7964FF2DB426ACB3C3505AA2A702DD5B689F45
  - &tim age14y022wl4kddtsl6r54s8r3s6j75qc4e4tshhxw6sugy06qlvwa7sgrjfqs
  - &test age1e8kc5qsacqf2mr7usl2lw8g74slmlga7w38qn5wyvgtzqe8z3dts4pwugj
  # Host keys
  - &laptop-02 age1tpm1qggj7xcx9f8a7aryv6cuwhxg0f67kxnrq0jd09amwudepachfk42z5n0g25
  - &desktop-02 age19zej0lsu5w6xqyey53mnc3r3cxvvdwckzezfc42vu8mplraf4y2shq90hl
  - &test-vm age1tpm1qvjmlh8tzjhtp4l89nmf7ylpu5qts4zn72x95vkg3r33au4vrc445g68jzf
creation_rules:
  - path_regex: configuration/secrets.yaml
    key_groups:
      - pgp:
          - *yubikey
        age:
          - *tim
          - *laptop-02
          - *desktop-02
  - path_regex: modules/users/test/secrets.yaml
    key_groups:
      - age:
          - *test
          - *tim
          - *test-vm
  - path_regex: modules/boxen/test-vm/secrets.yaml
    key_groups:
      - age:
          - *test-vm
          - *tim
  - path_regex: modules/boxen/laptop-02/secrets.yaml
    key_groups:
      - age:
          - *laptop-02
  - path_regex: modules/users/tim/secrets.yaml
    key_groups:
      - age:
          - *tim
          - *laptop-02
stores:
  yaml:
    indent: 2
