keys:
  # User keys
  - &yubikey 5D7964FF2DB426ACB3C3505AA2A702DD5B689F45
  - &tim age14y022wl4kddtsl6r54s8r3s6j75qc4e4tshhxw6sugy06qlvwa7sgrjfqs
  # Host keys
  - &laptop-02 age136xxlufx2lvp5tvc8d7mx7y2qhq4vh4k973xdc9tcs2wtv592q6qeh0gag
  - &desktop-02 age19zej0lsu5w6xqyey53mnc3r3cxvvdwckzezfc42vu8mplraf4y2shq90hl
  - &test-vm age1tpm1qvjmlh8tzjhtp4l89nmf7ylpu5qts4zn72x95vkg3r33au4vrc445g68jzf
creation_rules:
  - path_regex: configuration/secrets.yaml
    key_groups:
      - pgp:
          - *yubikey
        age:
          - *tim
          - *laptop-02
          - *desktop-02
  - path_regex: modules/boxen/test-vm/secrets.yaml
    key_groups:
      - age:
          - *test-vm
          - *tim
stores:
  yaml:
    indent: 2
    
