# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4b352365-f38d-4323-8191-d91eac3974d4";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd" "subvol=rootfs" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/4b352365-f38d-4323-8191-d91eac3974d4";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd" "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/4b352365-f38d-4323-8191-d91eac3974d4";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd" "subvol=nix" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/4b352365-f38d-4323-8191-d91eac3974d4";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd" "subvol=log" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/4b352365-f38d-4323-8191-d91eac3974d4";
      fsType = "btrfs";
      options = [ "noatime" "compress=zstd" "subvol=swap" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AE1A-26E6";
      fsType = "vfat";
    };

  swapDevices = [ { device = "/swap/swapfile"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
